### ISSUE TITLE
Setting SelectField multiple prop

### ISSUE THREAD

**Issue by kdavidmoore** [erikras/redux-form-material-ui#116]
How can I set the `multiple` prop of the SelectField component to `true` (as per [material-ui docs](http://www.material-ui.com/#/components/select-field))?

I tried putting `multiple` on the `Field` component, and it does get passed down to `SelectField` in the DOM as `multiple=true`, but the prop seems to have no effect on the behavior of the component. In other words, it behaves as if `multiple` were `false`.

Example code:
```
<Field name={this.getDynamicName()} component={SelectField} floatingLabelText={this.getDynamicLabel()} hintText="Select..." multiple>
    {this.renderMenuItems()}
</Field>
```

**Comment by jmenglis** [comment]
Interesting.  I am able to get the `multiple` functionality to start triggering the expected behavior.  The problem I have after is manipulating the state in the redux store while using seamless-immutable.  I noticed that `SelectField` uses `DropDownMenu` which calls a method `handleMenuItemTouchTap`.  `handleMenuItemTouchTap` uses `array.push` and `array.splice` to manipulate the change of value.  Not sure if these two are related but it could be why you are not seeing any items add to your state.

**Comment by kdavidmoore** [comment]
Ah, I'm using `redux-form/immutable` with `react-boilerplate`, so that's probably the issue.

**Comment by jmenglis** [comment]
It appears Material-Ui is going to make changes so you can access the properties of the component  not sure the intended release for it though but you can see it [here](https://github.com/callemall/material-ui/pull/6501)

**Comment by takealuke** [comment]
Hello @kdavidmoore -- I see that this issue was closed, but I'm not sure I understand the solution? I'm running into a similar (if not the same) issue trying to create a "multiselect" with this library.

Are you able to illustrate how you solved this?

**Comment by MetteRussell** [comment]
I have the same problem as @takealuke . 
Even though I have multiple={true} on SelectField, I can see the index in 
handleChange is set.
According the the documentation, index should be undefined if multiple={true}
